codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "test/**/*"
  - "**/*_test.go"
  - "cmd/**/*"
  - "vscode-extension/**/*"
  - "docs/**/*"
  - "*.md"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
